### ISSUE TITLE
EFB: Pdf-Files  not showing when selected in the "Pinned Charts" tab

### ISSUE THREAD

**Issue by dlh2gy** [flybywiresim/aircraft#8710] opened 2024-06-27 20:42 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-06-27T11:32:46+00:00",
    "ref": "refs/heads/master",
    "sha": "a31677734a166bccd11e2f2e3c3bf9251df80cee",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "master:a3167773",
    "version": "a32nx-v0.12.0-dev.a316777"
}
```

### Describe the bug

My charts are stored in "C:\Users\mdoc5\AppData\Local\MSFSPackages\Community\flybywire-externaltools-simbridge\resources\pdfs" as Pdf files. They are correctly listed in the  "Local Files" tab on the Navigation&Charts page of the EFB. When I select a chart from the list, it is correctly displayed. I can also pin the charts, and the pinned charts are shown as icons on the "Pinned charts" tab. When I then click an item to display the chart, the chart window remains blank and shows the text "chart" in the top left corner. In order to get the chart displayed, I need to switch back to the "Local Files" tab and select the chart via the list on the left.

Screenshot 1: chart selected and pinned - chart is correcly displayed
Screenshot 2: pinned charts correctly displayed as icons on "Pinned charts" tab
Screenshot 3: after clicking a chart icon on the "Pinned charts" tab, the "Local files" tab becomes active but the chart is not displayed, only the text "chart" in the top left corner
Screenshot 4: after clicking the list entry on the left, a pop-up showing "Loading PDF" shows up for about one second and thereafter the  chart is correctly displayed

![Screenshot1](https://github.com/flybywiresim/aircraft/assets/174055172/34392833-6b23-4404-aeb8-bbd8ad867442)
![Screenshot2](https://github.com/flybywiresim/aircraft/assets/174055172/8cc7f186-e04b-4de9-ba63-e1c165e382d9)
![Screenshot3](https://github.com/flybywiresim/aircraft/assets/174055172/b9721b15-c8fc-4f46-8b4e-30d97c68fc13)
![Screenshot4](https://github.com/flybywiresim/aircraft/assets/174055172/31fdcfd8-7de7-4747-9fbb-391dad31fd95)

### Expected behavior

Would expect that when an icon is clicked on the "Pinned charts" tab, the chart gets displayed (rathter than showing the "chart" text in the top left corner)

### Steps to reproduce

1. Go to "Local Files" tab of the "Navigation& Charts" tab and pin an item in the list
2. Go to "Pinned Charts" tab, and click the pinned item in step 1
3. Check if chart gets displayed, or if text "chart" is shown in top left corner

### Additional info (optional)

The issue persists since an update approximately two weeks ago, before it worked perfect.
With the same update, there was another change: before the update when the Navigation&charts page was selected the first time with a Simbrief flight plan already loaded,  the filter text  box (marked in red in Screenshot 5) box would be populated with the "From" airport identifier and the list below would only display elements whose filename contain the identifier
SInce the update, the filter text box remains empty and the list will try to display all files in the folder "C:\Users\mdoc5\AppData\Local\MSFSPackages\Community\flybywire-externaltools-simbridge\resources\pdfs"

If there is a too large number of files in this folder, this will crash the flight simulator! It seems that this is a sort of "index out of range" isssue, e.g. as if the list is allocated for say 10000 entries but the number of files in the folder is 12000. Perhaps this could be prevented by either
(1) increasing the list allocation size 
(2) implementing a populaton limit, i.e. stop adding list entries when the list size is reached

My full chart set comprises >40000 charts, which crashes  the sim with the current development version. With the earlier releases, this was no issue when the Simbrief flight plan was loaded before the Navigation&Chart page was opened the first time because the list was filtered for the "From" airport.
With the current release, I can only store a subset of files in the folder to prevent the crashes
![Screenshot5](https://github.com/flybywiresim/aircraft/assets/174055172/8f5b4c2f-7803-479c-b006-741d46e1a886)

### Discord Username (optional)

tui1rg

**Comment by XavierC713** [comment] 2024-07-15 07:18
I've been having the same issue, gonna take a look at the relevant code and see if I can implement a fix

**Comment by yourcptainspeaking** [comment] 2024-07-15 09:15
I now have a good idea of what's causing the issue and I'll submit a pull request with the fix later today

**Comment by dlh2gy** [comment] 2024-07-15 16:41
Hello Xavier,

good to hear, that is great news. I got so accustomed to the PDF-Feature of
the EFB that I don't want to miss it.

Can I also suggest one more thing (I am not sure whether that was the case
before): if you select a chart, it would be preferable to have the chart
fully displayed in the EFB. If I remember correctly, at the moment when you
pick a chart it is shown zoomed in and only partly displayed. You have to
click the "show full" icon to get the card fully shown on the display.

Thanks a lot for your effort to fix this. Let me know if I can somehow
help, e.g. by testing it.

Greetings
Rolf

Am Mo., 15. Juli 2024 um 11:16 Uhr schrieb Xavier Caldwell <
***@***.***>:

**Comment by yourcptainspeaking** [comment] 2024-07-15 18:14
Displaying the full chart should be easy to implement, I'll include it in the pull request. If you'd like to test it, the pull request will be linked in here when I submit it. It will include a modified build of the aircraft containing my changes as well as testing instructions. Thanks!

**Comment by dlh2gy** [comment] 2024-07-15 19:31
Hi Xavier,
another observation (apologies for my incremental suggestions): in the
past, if you had loaded a simbrief flightplan before changing to the "local
files" tab on the "Navigation and Charts" tab it would have the "From" tab
selected showing the charts from the departure airport in the list (e.g.
charts starting with KORD when O'Hare would be the departure airport)
At the moment the filename textbox is empty and it would (try to) display
all charts in the resource\pdfs folder in the list of the EFB (see
attachment). If there are too many files in this folder, it will crash
FS2020. It seems as if the list was sized for a fixed number of elements
and if the number of files in the resource folder exceeds this size, it
results in a kind of out of bounds error. In the past, this could happen
only if you hadn't imported the Simbrief flightplan before opening the
"Local Files" Tab on the "Navigation and Charts" page.

My charts folder holds > 60000 charts, which inevitably would cause a crash
(it didn't in the past when it showed only the "From" items after having
loading the Simbrief flight plan). At the moment, I have moved the majority
of the charts to a different folder and it works with 5000 files.
Not sure whether one of the following two options could be implemented:
(1) dynamically size the list depending on the number of files in the
resource\pdfs folder
(2) stop populating the list if the end of list is reached (at the expense
of not displaying all files)

I hope my description makes kind of sense. Let me know if clarification is
needed.

Again thanks for looking into this. The EFB charts is such a great feature,
in particular for online flying.

Greetings
Rolf





Am Mo., 15. Juli 2024 um 20:15 Uhr schrieb Xavier Caldwell <
***@***.***>:

**Comment by yourcptainspeaking** [comment] 2024-07-15 19:56
I can look into this, probably gonna end up limiting how many charts can be displayed since allowing an unlimited amount could lead to possible performance issues. Not sure if it will end up in this PR or a separate one as it might be out of scope for the original issue.

**Comment by yourcptainspeaking** [comment] 2024-07-15 21:35
The linked PR will fix the original issue. I couldn't find the cause of the crash since the array used for displaying the list of charts already has an unlimited size. It will probably still be fixed by implementing a limit on how many are displayed but I'm unable to fix it right now because I won't be home for another week after today. I'd recommend opening another issue so someone else can work on it. Thanks for reporting!

**Closed** 2024-07-19 10:54 UTC
Labels: Bug
