### ISSUE TITLE
Cabin terxture issu "Chess board"

### ISSUE THREAD

**Issue by Siberier** [flybywiresim/aircraft#8784] opened 2024-07-31 03:45 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-07-28T13:25:31+00:00",
    "ref": "refs/heads/master",
    "sha": "5d3514841d8c554bd1b7402e0a4295f01dd10f11",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "master:5d351484",
    "version": "a32nx-v0.12.0-dev.5d35148"
```

### Describe the bug

cabin texture issue after loading the aircraft. Look like a Chess board
![Screenshot 2024-07-31 103731](https://github.com/user-attachments/assets/880aa927-f55a-45a7-969f-ab35171b86cb)

### Expected behavior

Just fix this issue

### Steps to reproduce

1
2
3

**Comment by alepouna** [comment] 2024-07-31 04:08
This issue is usually caused by a bad livery, or conflicting addons. Please try and remove all other mods/liveries from the community folder and test our addon again. This will help rule out mod conflicts.

See [this step](https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#test-with-only-the-a32nx-add-on-in-community) in our troubleshooting guide for more details on how to do this easily.

If after having a clean community you still have this issue, we suggest trying a clean install. Please see [this guide](https://docs.flybywiresim.com/fbw-a32nx/installation/#clean-install-steps) for detailed instructions.

For more assistance, we recommend asking in our Discord server https://discord.gg/flybywire
Closing this issue as 'Won't fix' as it's not an aircraft issue, and the above recommendations have been proven to solve the issue.

**Closed by alepouna** 2024-07-31 04:08 UTC
Labels: Bug
