### ISSUE TITLE
Airstairs are not working properly at airports providing this service.

### ISSUE THREAD

**Issue by Flaxx-Rat** [flybywiresim/aircraft#8353] opened 2023-12-30 13:33 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-12-29T21:01:10+00:00",
    "ref": "refs/heads/master",
    "sha": "68bf94051aa8f37925b5b629624c80c9813721be",
    "actor": "beheh",
    "event_name": "manual",
    "pretty_release_name": "master:68bf9405",
    "version": "v0.12.0-dev.68bf940"
}
```

### Describe the bug

At airports providing airstairs it is impossible boarding or deboarding the PAX if not done instantly. The airstair drives away while deboarding is still in progress (at least in fast setting). The same happens when starting a flight at such gates. The airstair is driving towards the plane and even the crew wouldn't have the chance to enter as it nearly immediately drives away again.

### Expected behavior

Once called, the airstair should remain until explicitly released or until the plane is ready for push-back.The behaviour should be similar to jetways. When arriving the gate jetways are starting the docking process automatically and until release or when calling the pushback truck. If not parked the access to an aircraft should be possible anytime (service & crew included).

### Steps to reproduce

1. Place the bird e.g. at EDDB (Aerosoft), Gate D 13 or any other spot at the D or E ramp (or after arrival)
2. Call the jetbridge (here aka airstair)
3. It will come and dock on (often with a final funny side step, BTW)
4. Switch the EFB to "Payload" start boarding or deboarding (setting "Fast")
5. The airstair will leave while PAX are boarding or deboarding

### References (optional)

![image](https://github.com/flybywiresim/aircraft/assets/109431387/97c85be1-2356-47f3-987a-46a6d31ffcbc)

### Additional info (optional)

AFAIK it never worked differently in the past (probably it isn't even in your hands).

**Comment by Vitold69** [comment] 2024-01-02 20:10
The same for baggage door and right aft doors, baggage carts and catering truck. They move away too quickly. Say in 30 sec. Should stay until I click corresponding button on EFB to disconnect these services.

**Comment by Flaxx-Rat** [comment] 2024-01-03 15:47
You're right, but I can't see it from the cockpit - it's less disturbing.  ;-)

**Comment by SmokeyYT1** [comment] 2024-01-03 16:08
Which Script do you use?

**Comment by Flaxx-Rat** [comment] 2024-01-03 18:43
> Which Script do you use?

??? Honestly, I don't understand your question. It's just the "Services" Page of the FBW EFP. There you can tick some services, like external power, fuel (being not combined with the loading of fuel).

**Comment by frankkopp** [comment] 2024-02-01 17:35
This is not a bug but how the sim's vehicles work. We have looked into this in the past and we would have to either overwrite the default vehicles (as TBP does for example) or provide our own vehicles. 
The latter is on our extended roadmap but completion of the aircraft has priority. 
This will be closed as it is working as expected.

**Closed by frankkopp** 2024-02-01 17:35 UTC
Labels: Bug
