### ISSUE TITLE
Greendot indicator in the wrong position during cruise or after a step climb

### ISSUE THREAD

**Issue by Beedan1G** [flybywiresim/aircraft#9219] opened 2024-10-31 20:48 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T14:33:02+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "f26029363ad3edeeafbed20aa79c13b32c8090f8",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-HEAD.f260293"
}
```

### Describe the bug

Green dot inside red tape speed when in cruise, showing in the screenshot at 320 but should be below your cruise or managed speed

### Expected behavior

Should be below you managed speed and in the orange speed band

### Steps to reproduce

1.Need to be inflight/ Cruising
2. Look at your PFD after a period of time and see where the green dot is positioned
3. Maybe it could be cause of a step climb as I was originally at FL340 but then stepped to FL360

### References (optional)

![FlightSimulator_eRKoPXuyIg](https://github.com/user-attachments/assets/ea8f7a2e-c178-4728-90e9-181d803555c4)

**Comment by BlueberryKing** [comment] 2024-10-31 21:02
Duplicate of #9183

**Closed by BlueberryKing** 2024-10-31 21:02 UTC
Labels: Bug, A380X
