### ISSUE TITLE
All 4 Engines oil quantities are indicating 0.0 quatz.

### ISSUE THREAD

**Issue by G-DRAW** [flybywiresim/aircraft#9584] opened 2024-11-24 17:12 UTC
### Aircraft Version

Stable

### Build info

```json
"Master"
```

### Describe the bug

The oil quantities on all 4 engines are showing 0 oil quantities.
![A380X oil quantities](https://github.com/user-attachments/assets/ea128a36-4859-4e0f-8df0-21a5b3efb73f)

### Expected behavior

A380 FCOM Reference Data
![A380 Oil Data](https://github.com/user-attachments/assets/d041e459-25b2-4a88-ab68-78be7749f89e)
![A380 Oil Data P2](https://github.com/user-attachments/assets/eef4f808-2daf-4c79-ad76-90588385ae7f)

### Steps to reproduce

1. Establish AC electrical power on the Aircraft
2. Select Engine synoptic page on lower ECAM display.
3. Turn on 4 Ground FADEC Power on Maintenace Panel, or Engine Mode Selector to Ignition start or Crank.
4. Check oil quantity indications.

**Comment by Pruznak** [comment] 2024-11-24 17:58
I think this is expected currently, but will be fixed by #9368 Also, a duplicate of #9258 ?

**Comment by tracernz** [comment] 2024-11-24 18:53
Duplicate of #9258.

**Closed by tracernz** 2024-11-24 18:53 UTC
Labels: Bug, A380X
