### ISSUE TITLE
Take off calculator and taxi charts

### ISSUE THREAD

**Issue by pjetruu** [flybywiresim/aircraft#8509] opened 2024-02-18 18:08 UTC
### Aircraft Version

Development

### Description

Is it possible or if you are ever gonna add a take off calculator in efb. Would be great to add a direct navigraph connection for new taxi charts

### Discord Username (optional)

pjetruu

**Comment by Benjozork** [comment] 2024-02-18 18:16
Partly a duplicate of #4444. Please open separate tickets for separate suggestions

**Closed by Benjozork** 2024-02-18 18:16 UTC
Labels: Request
