### ISSUE TITLE
Small request

### ISSUE THREAD

**Issue by TWITCHGAMER34** [flybywiresim/aircraft#8521] opened 2024-02-24 16:45 UTC
### Aircraft Version

Development

### Description

I would like to request so that the ND displays the go around route, and it also is displayed in the FMGC

**Comment by Benjozork** [comment] 2024-02-24 16:53
Duplicate of #1835

**Comment by Benjozork** [comment] 2024-02-24 16:53
Additionally, please also indicate the actual request in the title next time. Thanks!

**Closed by Benjozork** 2024-02-24 16:53 UTC
Labels: Request
