### ISSUE TITLE
New Variants 

### ISSUE THREAD

**Issue by AgniveshNandan** [flybywiresim/aircraft#8683] opened 2024-06-18 05:59 UTC
### Aircraft Version

Stable

### Description

The FBW team should come out with other variants of the aircraft as well. Such as the normal A320-200, the A319, the A321.....etc. It will be a long term project but we will wait patiently for the experience we have been waiting for. Also, please put out some news on the release date of the A380. 

Thanks!

**Comment by Pruznak** [comment] 2024-06-18 06:44
I think first, the default A320neo should be somehow completed, including all the systems, failures, switches, buttons, modeled cabin, etc. which is still a lot of work to do (although I'm not a fbw dev, I don't know exactly), then, we may get other aircraft and engine variants.

**Comment by LunakisDev** [comment] 2024-06-18 06:47
The roadmap explains perfectly what the team wants to do first before making new variants

![roadmap](https://github.com/flybywiresim/aircraft/assets/71980142/e017be1c-7764-42ef-9468-e7d4ebe07cb0)

**Comment by AgniveshNandan** [comment] 2024-06-18 07:49
Yes you're absolutely right. That's exactly why I wrote that we will wait
patiently.

Happy Flying!

**Comment by Benjozork** [comment] 2024-06-30 04:47
Duplicate of #1408

**Closed by Benjozork** 2024-06-30 04:47 UTC
Labels: Request
