### ISSUE TITLE
During the first turnaround, the FMS is not reseting all of the entry fields.

### ISSUE THREAD

**Issue by G-DRAW** [flybywiresim/aircraft#9499] opened 2024-11-12 19:57 UTC
### Aircraft Version

Stable

### Build info

```json
N/A
```

### Describe the bug

During the descent phase, the aircraft didn't revert back to SPD reference automatically on the AFS CP.
![A380X on Ground with Speed units stuck in MACH](https://github.com/user-attachments/assets/3e0cb239-dc7b-40fe-a1e2-9341c67df182)

After landing and taxiing to the apron parking stand, I was going to operate a turnaround flight and I found that the FMS and FD's has not reset itself automatically after landing and rollout.

Some of my new flight plan entered on the INIT Page was in white such as the: FROM, TO Airports, CPNY RTE, ALTN RTE and Cost Index.
![A380X FMS INIT Page](https://github.com/user-attachments/assets/b8f1706e-ef72-42a5-877a-b9e7fc0c99bf)

On the FUEL & LOAD Page I cannot insert the new BLOCK Fuel, and the Cost index is displayed in white.
![A380X FMS FUEL   LOAD Page](https://github.com/user-attachments/assets/bcf52041-701c-4fd8-bbf2-d90e84967f63)

On the PERF pages, it is still displaying the GA Page on the ground, even after inserting the new flight plan in the INIT Page.
![A380X FMS GA Page](https://github.com/user-attachments/assets/a28c4a18-8ec7-4ff4-ba88-74eea79ccd15)

Also I could not enter my new V speeds, or enter T.O Shift, Flaps settings, Packs or Anti Ice selections, THS FOR, THR RED ALT, ACCEL ALT, EO ACCEL ALT or select either a TOGA or FLEX on T.O PERF Page, apart from Transition Altitude.
![A380X FMS T O Page](https://github.com/user-attachments/assets/b45e9587-dfb4-40a7-a12d-f4b7b740f49b)

### Expected behavior

On the other flights that I conducted on my PC, the aircraft automatically changed from SPD to MACH, and from MACH back to SPD references units automatically without issues.

Both the FD's and FMS's should automatically reset themselves after the landing and rollout phase of operation, which usually occurs at a speed of less that 10kts GS.

The entry fields on the INIT Page should all be blue, authough I have had no issues uplinking and inserting my new flightplan.

On the FUEL & LOAD Page the BLOCK fuel should be displayed, and the CI number be blue. I was able to load in the ZFW and the ZFWCG.

On the PERF Page, it should default to the T.O Page, from the GA Page.

Also should be able to enter all required T.O PERF fields, and modify Thrust selection, flap settings, Pack settings and Anti Ice settings.

### Steps to reproduce

I tried manually resetting the FD's, which didn't seem to work.

Currently the best option is to come out of the simulator and load back into the aircraft.

Or reload simbrief.

On flights that go one way with no turnarounds, the FMS systems work just fine and handle things they should.

**Comment by tracernz** [comment] 2024-11-13 00:02
Duplicate of https://github.com/flybywiresim/aircraft/issues/9019

**Closed by tracernz** 2024-11-13 00:02 UTC
Labels: Bug, A380X
