### ISSUE TITLE
SIDS for airport LFBO are incorrectly numbered

### ISSUE THREAD

**Issue by StephN-B** [flybywiresim/aircraft#9260] opened 2024-11-01 08:35 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

While preparing the F-PLN for departure, the SIDs are incorrectly numbered. All numbers are one down from what is correct,
For example:
instead of 
- AMOL7A I see AMOL6A
- MEN7A I see MEN6A

### Expected behavior

SIDs should be numbered correctly.

### Steps to reproduce

1. Create SIMBRIEF flight plan LFBO - EDDM
2. Load plan
3. Proceed to Departure page
4. Select runway 14R
5. Get list of SIDs -> instead of e.g. MEN7A you will see MEN6A

### References (optional)

**LIST OF CORRECTLY NAMED DEPARTURES**
![image](https://github.com/user-attachments/assets/73beb714-f85e-4afd-99d1-f242347f612e)

**AS DISPLAYED IN FMS**
![image](https://github.com/user-attachments/assets/7e4a8b2f-6767-465d-ae7d-3182d46da616)

### Additional info (optional)

In case this matters:
- I am using the Standard Livery
- Installed the 4K version

**Comment by GeorgeBarlow** [comment] 2024-11-01 08:58
What AIRAC cycle do you have installed?

**Comment by AmazinAmazon** [comment] 2024-11-01 13:05
This isn't a bug, you just don't have your AIRAC up to date.

**Comment by alepouna** [comment] 2024-11-01 18:24
Closed as it's not a bug, see comments above.

**Closed by alepouna** 2024-11-01 18:24 UTC
Labels: Bug, Invalid, A380X

**Comment by tracernz** [comment] 2024-11-02 07:04
They are numbered correctly in the MSFS base navdata, so it must be something you have installed on top.
