### ISSUE TITLE
Small Bug when deboarding on the EFB

### ISSUE THREAD

**Issue by Kurnusos** [flybywiresim/aircraft#8196] opened 2023-09-04 20:20 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-09-04T02:30:14+00:00",
    "ref": "refs/heads/master",
    "sha": "12c8e357bccc95d58b6fab4d2e2051ca6b9940fb",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:12c8e357",
    "version": "v0.11.0-dev.12c8e35"
}
```

### Describe the bug

When using the EFB to deboard people, when you click on the deboard button, it doesn't actually deboard. I get the sound "boarding completed" get the audio from the "captain" and that's it. I'd then have to click on it again to actually deboard the passengers of the plane.

It's a small bug and nothing really much compared to probably other bugs, but I thought I'd just let you know.

### Expected behavior

Deboard the plane straight away and not have the "audios" of "boarding completed" and "captains audio" playing.

### Steps to reproduce

1. Board the passengers
2. Press Deboard on the EFB

### Discord Username (optional)

gh0stpred

**Comment by 2hwk** [comment] 2023-09-05 11:21
Duplicate of https://github.com/flybywiresim/aircraft/issues/8196 closing

**Closed by 2hwk** 2023-09-05 11:21 UTC
Labels: Bug
