### ISSUE TITLE
COM_RADIO controls are non-functional

### ISSUE THREAD

**Issue by richardkennedy** [flybywiresim/aircraft#9271] opened 2024-11-01 13:05 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

The following MSFS controls are non-functional, preventing the frequencies from being modified via FSUIPC7.

65636   COM_RADIO_WHOLE_DEC
65637   COM_RADIO_WHOLE_INC
66372   COM_STBY_RADIO_SWAP

### Expected behavior

The controls should increase/decrease the frequencies and allow them to be swapped between STBY/ACT.

### Steps to reproduce

Call the listed controls via FSUIPC7.

**Comment by tracernz** [comment] 2024-11-01 13:28
Thanks. Duplicate of https://github.com/flybywiresim/aircraft/issues/8951

**Closed by tracernz** 2024-11-01 13:28 UTC
Labels: Bug, A380X
