### ISSUE TITLE
Sim event `COM_STBY_RADIO_SWAP` does not swap the active and standby frequency

### ISSUE THREAD

**Issue by BjoernHund** [flybywiresim/aircraft#9462] opened 2024-11-09 10:44 UTC
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-09T01:50:24+00:00",
    "ref": "refs/tags/v0.12.2",
    "sha": "f05102ab846b402136e3f06e65b65e7c08b1cc8c",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.2",
    "version": "a380x-v0.12.2-rel.f05102a"
}
```

### Describe the bug

Some time ago I wrote a small external tool with which I can set the COM frequencies for the MSFS. This makes the frequency changes easier for VATSIM.

It work's nice with the A20NX and other planes. But in the A380, I can not switch between the standby and the active frequency.

I use the `COM_STBY_RADIO_SET_HZ` event to set the standby frequency and the `COM_STBY_RADIO_SWAP` event to swap the frequency.

I know, that the plane is still in an alpha state, but perhabs some of the developers can have a look into it.

### Expected behavior

It would be nice, to change the COM frequencies with the standard MSFS sdk.

### Steps to reproduce

1.  Start a new flight at a gate
2. Turn on external power and batteries
3. Start the RadioPanel application
4. Enter a new standby frequency and hit enter
5. Push the toggle button between the active and the standby frequency

### References (optional)

![image](https://github.com/user-attachments/assets/68200506-f6f8-4ead-b63c-b8505ba3c84e)

![image](https://github.com/user-attachments/assets/2017fd4b-7a59-4306-85b8-246075f7cb92)

![image](https://github.com/user-attachments/assets/2b299f30-540a-4e24-8ce8-4cf24a75b381)

### Additional info (optional)

https://github.com/BjoernHund/RadioPanel/tree/master

https://github.com/BjoernHund/RadioPanel/blob/master/src/FsConnect/Managers/RadioManager.cs#L116

### Discord Username (optional)

thequietsmile

**Comment by tracernz** [comment] 2024-11-09 10:51
Duplicate of https://github.com/flybywiresim/aircraft/issues/8951

**Closed by tracernz** 2024-11-09 10:51 UTC
Labels: Bug, A380X
