### ISSUE TITLE
Erronous reflection on forward cockpit windows

### ISSUE THREAD

**Issue by BER811** [flybywiresim/aircraft#9441] opened 2024-11-07 18:59 UTC
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

There is a reflection of the display units and other illuminated stuff visible on the windscreen, which are not possible in reality, due to the glareshield extends over those sources of light. Its virtually impossible to reflect beyond the glareshield and as I am a pilot, I can asure, that there are no such reflections on the windscreen.

### Expected behavior

No reflecting isntruments on the windscreen.

### Steps to reproduce

Fly at night and look at the forward windscreen.

### References (optional)

![380 wrong reflection](https://github.com/user-attachments/assets/f158a0ff-4933-4106-b54a-2d13343ced8a)

**Comment by Benjozork** [comment] 2024-11-07 19:01
Duplicate of #9380, not something we can fix. Just how screen space reflections work. Won't be correct without ray traced reflections.

**Comment by flogross89** [comment] 2024-11-07 19:01
Indeed, these reflections are unrealistic. Unfortunately, there's nothing we can do, since MSFS doesn't offer raytracing and thus doesn't offer realistic reflections

**Closed by Benjozork** 2024-11-07 19:01 UTC
Labels: Bug, A380X

**Comment by BER811** [comment] 2024-11-07 19:02
Okay, thanks for the clarification!

**Comment by BER811** [comment] 2024-11-07 19:43
Hi Benjamin,
 
I'd like to come back here.
Why isn't that a case with other planes? I am a Beta tester for over a decade now and have never seen anything in MSFS like with the A380, why?
If thats a limitation by the sim, all would have to suffer but they don't, so why do you have that issue then?
 
Best regards
Sven


Gesendet: Donnerstag, 7. November 2024 um 20:01
Von: "Benjamin Dupont" ***@***.***>
An: flybywiresim/aircraft ***@***.***>
CC: BER811 ***@***.***>,Author ***@***.***>
Betreff: Re: [flybywiresim/aircraft] Erronous reflection on forward cockpit windows (Issue #9441)

 
Duplicate of #9380, not something we can fix. Just how screen space reflections work. Won't be correct without ray traced reflections.

**Comment by Benjozork** [comment] 2024-11-07 19:49
> Hi Benjamin,
>
> I'd like to come back here.
> Why isn't that a case with other planes? I am a Beta tester for over a decade now and have never seen anything in MSFS like > with the A380, why?
> If thats a limitation by the sim, all would have to suffer but they don't, so why do you have that issue then?
> 
> Best regards
> Sven

How much you notice it will definitely depend on the size of the instruments on your screen, the angle of the geometry, etc.

I recently saw this exact issue in a stock airplane. It is just probably more noticeable in the A380 for a variety of reasons.

**Comment by BER811** [comment] 2024-11-07 20:36
Is it possible, it also depends on the collision model?I noticed I cannot zoom in VR as you don't have a collision model in the cockpit. I can translate through all the cockpit walls using the camera system. When using the PMDG 777 for example, its not possible, I hit the wall and the camera movement stop. I don't wanna argue as in the end its your guys plane, but we have at least identical display amounts in the 777 and don't have this issue. This is very annoying when you fly in VR. I have to switch off the reflection in the dark to be able to fly with the A380.Its a lovely plane except the cruel performance.Hopefully there is a solution or at least with MSFS 2024.Am 07.11.2024 um 20:50 schrieb Benjamin Dupont ***@***.***>:﻿

Hi Benjamin,
I'd like to come back here.
Why isn't that a case with other planes? I am a Beta tester for over a decade now and have never seen anything in MSFS like > with the A380, why?
If thats a limitation by the sim, all would have to suffer but they don't, so why do you have that issue then?
Best regards
Sven

How much you notice it will definitely depend on the size of the instruments on your screen, the angle of the geometry, etc.
I recently saw this exact issue in a stock airplane. It is just probably more noticeable in the A380 for a variety of reasons.

**Comment by gilbnx** [comment] 2024-11-07 23:15
I'd like to echo @BER811. This is a great airplane but in VR, the reflections on the windshield is probably becasue the glareshield is potentially "trnaspanet"? Same reason we can move through the walls in VR? Maybe this is why the glareshield is not doing it's job and the zoom is not functioning as with other Mods? Will be really appreciated if the cockpit VR can be corrected. Btw, I have a similar bug open on VR where the keyboard in some cases also becomes "transparent" and cannot be clicked on... Maybe related?

**Comment by flogross89** [comment] 2024-11-08 00:00
I think now you're just mixing up completely unrelated issues. We stated reasons for this bug, no point discussing this.

**Comment by BER811** [comment] 2024-11-08 07:11
He might have a valid point thought.Of course its your guys software and its great to have a plane for free like this, and I honestly grateful for this.But if this is strictly MSFS related, then all aircraft would have this issue to a certain degree, but in fact I don't know any to be honest. Never seen that in any other aircraft.Again, we just like to help finding the issue, not putting any pressure on you guys. Am 08.11.2024 um 01:00 schrieb floridude ***@***.***>:﻿
I think now you're just mixing up completely unrelated issues. We stated reasons for this bug, no point discussing this.
