### ISSUE TITLE
baro preselection unit not cooresponding to the unit selected when in STD mode.

### ISSUE THREAD

**Issue by JulKem** [flybywiresim/aircraft#9199] opened 2024-10-31 17:22 UTC
### Aircraft Version

Development

### Build info

```json
"built": "2024-10-31T14:33:02+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "f26029363ad3edeeafbed20aa79c13b32c8090f8",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-HEAD.f260293"
}
```

### Describe the bug

pre selection of  the qnh  stays in the mode selected before witching to  STD. The inHg/hPa selector has no effect when  in STD mode.

### Expected behavior

preselection should display according to the unit selected.

### Steps to reproduce

1.  use one mode to set bar.
2. pull for std mode
3. switch unit while in std mode
4. preselection will display in the unit selected before switching to STD.

### Discord Username (optional)

JulK

**Comment by 2hwk** [comment] 2024-10-31 17:29
Fixed by https://github.com/flybywiresim/aircraft/pull/9164

**Comment by 2hwk** [comment] 2024-10-31 17:30
Duplicate of https://github.com/flybywiresim/aircraft/issues/9161 actually, closing.

**Closed by 2hwk** 2024-10-31 17:30 UTC
Labels: Bug, A380X
