### ISSUE TITLE
Terrain on 640NM shows pink far ahead

### ISSUE THREAD

**Issue by VeIocityy** [flybywiresim/aircraft#9295] opened 2024-11-01 22:43 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

When you have the TERR option on and have you ND view at 640NM, the terrain past ~600NM is pink.
![image](https://github.com/user-attachments/assets/06245d1c-549d-4e6d-bfda-02577d149cc8)

### Expected behavior

Show the correct terrain levels.

### Steps to reproduce

1. Load in anywhere.
2. Put your ND to 640NM range.
3. Turn on TERR mode.

### Discord Username (optional)

velocity.

**Comment by alepouna** [comment] 2024-11-02 03:50
Duplicate of #9236

**Closed by alepouna** 2024-11-02 03:50 UTC
Labels: Bug, A380X
