### ISSUE TITLE
 [A380X] Animation of FEED TK 4 MAIN and STBY switches are linked

### ISSUE THREAD

**Issue by beheh** [flybywiresim/aircraft#9099] opened 2024-10-19 15:04 UTC
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

When pressing the FEED TK 4 MAIN switch in the FUEL panel, both the the FEED TK 4 MAIN and the FEED TK 4 STBY switches are animated. When pressing the FEED TK 4 STBY switch nothing animates (except for the legend turning on/off).

### Expected behavior

The FEED TK 4 MAIN and FEED TK 4 STBY switches should animate independently.

### Steps to reproduce

Press the FEED TK 4 MAIN switch in the fuel panel. Observe both the FEED TK 4 MAIN  and FEED TK 4 STBY switches animating.

**Comment by BlueberryKing** [comment] 2024-10-20 10:26
Duplicate of #8943. Please do reopen if I misunderstood

**Closed by BlueberryKing** 2024-10-20 10:26 UTC
Labels: Bug, A380X
