### ISSUE TITLE
Throttle resetting to idle on takeoff with mouse input

### ISSUE THREAD

**Issue by rthom91** [flybywiresim/aircraft#8896] opened 2024-09-13 08:17 UTC
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-11-03T17:47:36+00:00",
    "ref": "refs/tags/v0.11.1",
    "sha": "f055eb02dc0af32441f8b2873f58e8316d7ca638",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.11.1",
    "version": "v0.11.1-rel.f055eb0"
}
```

### Describe the bug

Reference #7607 

Throttles drop to idle immediately once weight comes off rear wheels.

Problem is here: https://github.com/flybywiresim/aircraft/blob/713037fa6d25656469a93f898aa05bc5ac5fefea/fbw-a32nx/src/behavior/src/A32NX_Interior_Engine.xml#L80

### Expected behavior

Throttles stays at set position.

### Steps to reproduce

Spawn on runway.
Use mouse to throttle up.
Takeoff.

**Comment by tshomas** [comment] 2024-09-13 08:26
Hi, could you possibly check these settings below? These are known for causing an engine rollback when airborne?

![Screenshot_20240913-092528](https://github.com/user-attachments/assets/dbb490d3-96db-42cc-bd5b-9126e802d008)

**Comment by rthom91** [comment] 2024-09-13 08:40
https://github.com/flybywiresim/aircraft/issues/7607#issuecomment-1327948145

**Comment by tshomas** [comment] 2024-09-13 08:43
Wait did you open up a new issue when one was already open?

**Comment by tshomas** [comment] 2024-09-13 08:46
Duplicate of https://github.com/flybywiresim/aircraft/issues/7607#issue-1457071330

Recommend closure of this one.

**Comment by rthom91** [comment] 2024-09-13 08:46
> Wait did you open up a new issue when one was already open?

(eyeroll)
![ajdhj](https://github.com/user-attachments/assets/5627158e-51be-42a6-a9dc-5b2bd29dfbbc)

**Comment by BlueberryKing** [comment] 2024-09-13 08:51
> > Wait did you open up a new issue when one was already open?
> 
> (eyeroll) ![ajdhj](https://private-user-images.githubusercontent.com/47700786/367218066-5627158e-51be-42a6-a9dc-5b2bd29dfbbc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0OTYsIm5iZiI6MTcyNjIxNzE5NiwicGF0aCI6Ii80NzcwMDc4Ni8zNjcyMTgwNjYtNTYyNzE1OGUtNTFiZS00MmE2LWE5ZGMtNWIyYmQyOWRmYmJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA4NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1Yjg2ZjY0YjY0Mjk0MzJhZDA2NGFjNmI5NjhjOTlkYTQwZTRlYjJiMDhjNTM1NDU4ODg3NDBiNDU3ODQ5YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mqPBgm7JelzZZ26Zn7S_HnkeUrn0AN-moBdvedbRHrY)

We've identified this to be an issue when using the mouse to control the throttles. We do want to fix it, the original issue is still open, but you'll have to use the workaround described in Saschl's comment you linked until a fix is implemented. Thanks for understanding!

**Closed** 2024-09-13 08:51 UTC
Labels: Bug, A32NX

**Comment by rthom91** [comment] 2024-09-13 08:59
> you'll have to use the workaround described in Saschl's comment you linked until a fix is implemented.

Not possible over shared cockpit.
