### ISSUE TITLE
[A380X] ND doesn't display waypoints beyond 320NM arc

### ISSUE THREAD

**Issue by tic226n** [flybywiresim/aircraft#9365] opened 2024-11-03 15:18 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

When the ND range selector on the EFIS panel is set to 640 while ND mode 'ARC' is selected the ND only shows F-PLN WPs up to the 320NM arc, all subsequent WPs beyond that are missing from the range 320 - 640.

### Expected behavior

The ND should display all programmed WPs in a 640NM range when selected.

### Steps to reproduce

1. Enter F-PLN into FMS
2. Select ND mode 'ARC'
3. Select ND range of 640NM on the EFIS, WPs beyond 320NM distance are missing

**Comment by BlueberryKing** [comment] 2024-11-03 16:36
Duplicate of #9058

**Closed by BlueberryKing** 2024-11-03 16:36 UTC
Labels: Bug, A380X
