### ISSUE TITLE
Fuel not converted or labeled correctly on all pages when pounds is selected. 

### ISSUE THREAD

**Issue by CAC14** [flybywiresim/aircraft#9384] opened 2024-11-04 02:56 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

All these issues are when the plane is set to pounds for us USA pilots.  (set in Flypad)

First image shows "cruise" page but list KG.  The values are in pounds, but lableled in KG<img width="343" alt="image" src="https://github.com/user-attachments/assets/8e9be772-d2f6-4a67-9425-cc0789755050">

On the "fuel" page all value are in KG.  
<img width="397" alt="image" src="https://github.com/user-attachments/assets/6dc37f5f-01b9-4b8e-a71e-a9fa9743ea75">

On the "ENG" page all values are in KG.  
<img width="415" alt="image" src="https://github.com/user-attachments/assets/e5e8f652-1477-4382-845b-e05eb7f8dcab">

Here is the fly pad page showing its set to pounds.  
<img width="677" alt="image" src="https://github.com/user-attachments/assets/63a5b788-7241-435f-95aa-636325cf43c8">

### Expected behavior

I'd expect fuel to be listed in pounds when pounds is selected.  Also the cruise page should say pounds and not KG.

### Steps to reproduce

Load up sim.  
select pounds on flypad.
review cruise, eng and fuel page 

### References (optional)

a

### Additional info (optional)

a

### Discord Username (optional)

therealcrgaming

**Comment by tracernz** [comment] 2024-11-04 07:44
Duplicate of #9206.

**Closed by tracernz** 2024-11-04 07:44 UTC
Labels: Bug, A380X
