### ISSUE TITLE
[BUG] Engine Bleed air not available for engine start

### ISSUE THREAD

**Issue by Emile31** [flybywiresim/aircraft#820] opened 2020-09-23 09:21 UTC
**Mod Version**
Tested using 0.2.0 version the 23th of september 2020.

**Describe the bug**
For engine start on ground, it is not possible to perform the start with engine air bleed. It is working only with APU bleed.

**To Reproduce**
1. Start the game with aircraft on runway with engine running
2. Shutdown Engine1 with Master Lever Off
3. Try to restart it : Rotary to IGN and MasterLever 1 to ON, nothing is happening. We can see on ECAM SD page there is no air pressure.
(If we start the APU, and switch on the APU bleed, ten we can start.) 

**Expected behavior**
As engine 2 is running, they shall be bleed air available for the start.

**Actual behavior**
We can see on ECAM SD page the starter air valve opening, but still "0" air pressure.
The N2 is not increasing.

**Comment by Ares1378** [comment] 2020-09-23 14:40
This is not a bug. You cannot start the engine without bleed air. There is no bleed air when you do not have the apu on and the apu bleed on. The cross bleed valve  switch does not work yet... so there is no ability for a cross bleed start.

**Comment by Emile31** [comment] 2020-09-23 14:50
AH ok yes if the problem is the cross bleed valve stucked closed that makes sense.
I guess the bug/improvment for Xbleed valve is already open ?

**Comment by Ares1378** [comment] 2020-09-23 14:55
The X-bleed is always in Auto unless you do a crossbleed start. When the X-bleed selector sw is in auto the valve is open if the APU bleed valve is open and closed if the APU bleed valve is closed. You have to OPEN the X-bleed selector switch in order to tap air from Engine 2. The switch is currently stuck in AUTO only so there is no way to do a cross bleed start, please reference the above FCOM information for review.

**Comment by lousybyte** [comment] 2020-09-25 07:42
Related #144

**Comment by Emile31** [comment] 2020-10-01 07:54
Is there an action open to get a Xbleed valve functionning ?

**Comment by juliansebline** [comment] 2022-04-24 10:56
I'm on it

**Comment by patsta32** [comment] 2023-01-06 12:41
This should be fixed with AAU_01. 

From [Jan 05 Dev Update](https://www.flightsimulator.com/january-5th-2023-development-update/)

_We have fixed a longstanding issue where engine bleed air could not be used to start another engine. Now, you should be able to start other engines with engine bleed air as long as the running engine bleed air is selected or the bleed air system is set to AUTO. (AAU_01)_

**Comment by tracernz** [comment] 2023-01-07 02:55
I think it works even when it shouldn't now. At some point this can be fixed.

**Comment by tracernz** [comment] 2023-02-13 08:59
This should be possible for anybody to fix now.. the issue now is more stopping the crossbleed start when it shouldn't be available I think.

**Closed** 2023-09-07 11:10 UTC
Labels: Bug, Bug-Vanilla
