### ISSUE TITLE
Windshield Sun Shades

### ISSUE THREAD

**Issue by Lammmier** [flybywiresim/aircraft#8594] opened 2024-03-30 01:33 UTC
### Aircraft Version

Development

### Description

Maybe add a Windshield Sun Visor to make it not too sunny inside, the light comes in and makes everything shiny and it's killing my eyes.

**Comment by Maximilian-Reuter** [comment] 2024-03-30 09:58
Seems to be a duplicate of #4587

**Closed by Maximilian-Reuter** 2024-03-30 09:58 UTC
Labels: Request
