### ISSUE TITLE
Oil qty stuck on 0.0

### ISSUE THREAD

**Issue by Def9Infinite** [flybywiresim/aircraft#9221] opened 2024-10-31 21:03 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:50:20+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

Oil qty of engines are still displaying 0.0 after engine start

### Expected behavior

Should not be 0.0

### Steps to reproduce

1. Load aircraft with c&d
2. start engine, able to see that oil qty is being 0.0

### References (optional)

![image](https://github.com/user-attachments/assets/55b888dc-ab4e-49fa-9a5c-ad97240dd6d9)

### Discord Username (optional)

Def9Infinite

**Comment by tracernz** [comment] 2024-11-24 18:52
Duplicate of #9258 (keeping the newer one as it has more info attached).

**Closed by tracernz** 2024-11-24 18:52 UTC
Labels: Bug, Reproduced, A380X
