### ISSUE TITLE
TCA airbus throttle issues

### ISSUE THREAD

**Issue by Jordology** [flybywiresim/aircraft#8464] opened 2024-02-03 05:50 UTC
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-11-03T17:47:36+00:00",
    "ref": "refs/tags/v0.11.1",
    "sha": "f055eb02dc0af32441f8b2873f58e8316d7ca638",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.11.1",
    "version": "v0.11.1-rel.f055eb0"
}
```

### Describe the bug

FBW version 0.11.1 
MSFS version 1.36.2.0

When the tca throttle is at climb, the aircraft power is at 82.4%. I have calibrated multiple times and the detents are all correct even in the virtual throttle they are correct, but the aircraft power is at 82.4%

### Expected behavior

throttle power should be at climb

### Steps to reproduce

connect tca throttle
calibrate
turn on engines and everything else as normal
set throttle to climb

**Comment by Sleinmaster** [comment] 2024-02-03 07:25
82.4% for climb and even for Toga is completely normal. It very much depends on the outside conditions like temperature and pressure how many % N1 you'll get. 
Also the 100% N1 is some arbitrary number that was determined for one engine.type. The engines evolved since then and with have different maximum numbers.

**Comment by Jordology** [comment] 2024-02-03 07:30
Wait, so my throttle should be extremely sensitive? It was never like this before, has something been changed? Climb was always around 50% with these settings, what’s changed?

**Comment by Jordology** [comment] 2024-02-03 07:35
> 82.4% for climb and even for Toga is completely normal. It very much depends on the outside conditions like temperature and pressure how many % N1 you'll get. Also the 100% N1 is some arbitrary number that was determined for one engine.type. The engines evolved since then and with have different maximum numbers.

Wait so what should the power for each detent be? Climb has always been. Around 60 for me, quite confusing now haha. Has anything changed?

**Comment by jbud** [comment] 2024-02-03 12:27
There seems to be some confusion here. Can you share screenshots of your findings so we can clear it up?

**Comment by tracernz** [comment] 2024-02-04 03:55
Also check that you have setup a linear curve. The default MSFS TCA profile is not useful as it has a very odd curve.

**Comment by Jordology** [comment] 2024-02-05 08:51
> Also check that you have setup a linear curve. The default MSFS TCA profile is not useful as it has a very odd curve.

What should the settings be?

**Comment by Eearslya** [comment] 2024-02-05 08:54
> > Also check that you have setup a linear curve. The default MSFS TCA profile is not useful as it has a very odd curve.
> 
> What should the settings be?

Linear. As in, a straight line.

![image](https://github.com/flybywiresim/aircraft/assets/2270586/a752c191-e403-4beb-8753-21cd53da759a)

**Comment by Jordology** [comment] 2024-02-05 09:43
> > > Also check that you have setup a linear curve. The default MSFS TCA profile is not useful as it has a very odd curve.
> > 
> > 
> > What should the settings be?
> 
> Linear. As in, a straight line.
> 
> ![image](https://private-user-images.githubusercontent.com/2270586/302229319-a752c191-e403-4beb-8753-21cd53da759a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjY0NjksIm5iZiI6MTcwNzEyNjE2OSwicGF0aCI6Ii8yMjcwNTg2LzMwMjIyOTMxOS1hNzUyYzE5MS1lNDAzLTRiZWItODc1My0yMWNkNTNkYTc1OWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDk0MjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2QyMTBjMDQ3ZjI4ZWUzZDIyNmYzMTEwODRiNjg3MmQzODI2OTZhZGI4YWNhZTgwZjhlNzY1NTQ5MDBiMGRlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JwaoYq34047377JkVzhnyUpsAePfrDXInC0-f7zc3rE)

Yep, my calibration settings look like that. its not an issue with the throttle or the axis though, its the plane itself.

see below

![image](https://github.com/flybywiresim/aircraft/assets/158692520/eb0d76a6-ab9d-4a88-82bf-6c26e348e822)

**Comment by Eearslya** [comment] 2024-02-05 09:49
All of that looks perfectly fine to me. Like others have said already, CLB thrust doesn't necessarily mean 100% N1. Even TOGA doesn't necessarily mean 100% N1.

As long as the throttle in game matches your controller, it's calibrated correctly.

**Comment by Jordology** [comment] 2024-02-05 09:50
> There seems to be some confusion here. Can you share screenshots of your findings so we can clear it up?

posted above

**Comment by Jordology** [comment] 2024-02-05 09:52
> All of that looks perfectly fine to me. Like others have said already, CLB thrust doesn't necessarily mean 100% N1. Even TOGA doesn't necessarily mean 100% N1.
> 
> As long as the throttle in game matches your controller, it's calibrated correctly.

See its odd because its never done this before, climb has always been 50-60% (cant remember exactly)

**Comment by Sleinmaster** [comment] 2024-02-05 09:54
> > All of that looks perfectly fine to me. Like others have said already, CLB thrust doesn't necessarily mean 100% N1. Even TOGA doesn't necessarily mean 100% N1.
> > As long as the throttle in game matches your controller, it's calibrated correctly.
> 
> See its odd because its never done this before, climb has always been 50-60% (cant remember exactly)

In the upper right corner of the ecam the plane will tell you what detent it expects and what the max N1 for that detent is. In the case of your screenshot TOGA is limited to 83.4 % N1 and climb, once you've taken off, will probably be something similar.

![Screenshot_20240205-105136](https://github.com/flybywiresim/aircraft/assets/79196358/5ec55bc5-07ff-4275-b580-337b9356588e)

**Comment by Maximilian-Reuter** [comment] 2024-02-05 17:09
> > All of that looks perfectly fine to me. Like others have said already, CLB thrust doesn't necessarily mean 100% N1. Even TOGA doesn't necessarily mean 100% N1.
> > As long as the throttle in game matches your controller, it's calibrated correctly.
> 
> See its odd because its never done this before, climb has always been 50-60% (cant remember exactly)

You seem to be a bit confused over what the Autothrust does. The autothrust system will vary the thrust between idle and the current position of the thrustlevers. So if you have your thrustlevers in CLB it will modulate the thrust between idle and the maximum thrust it has calculated for the clb detent. usually during climb you will see values in the 80% range. In cruise it will depend on your speed.

In the end the thrust limits are dynamic and are calculated based on external factors like outside temperature and things like that.

**Comment by 2hwk** [comment] 2024-02-16 03:09
Not a bug, closing.

**Closed by 2hwk** 2024-02-16 03:09 UTC
Labels: Bug
