### ISSUE TITLE
[A380X] Unable to enter data in INIT page in turnaround

### ISSUE THREAD

**Issue by Letreivchen** [flybywiresim/aircraft#9147] opened 2024-10-26 21:06 UTC
### Aircraft Version

Development

### Build info

```json
"built": "2024-10-26T15:50:18+00:00",
    "ref": "refs/heads/v0.12",
    "sha": "8aed527070c9a9328f260295b5b861eb59704000",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "v0.12:8aed5270",
    "version": "a380x-v0.12.0-v0.12.8aed527"
```

### Describe the bug

After a previous flight it is not possible to fill data into the INIT page, possibly because it does not get reset when switching to the done phase

### Expected behavior

Should be able to fill data into the INIT page after a flight

### Steps to reproduce

Get to the Done phase ( for example after completing a flight) and try to fill data into the INIT page

### Discord Username (optional)

Letreiv

**Comment by macieksoft** [comment] 2024-10-31 20:38
![turnaround](https://github.com/user-attachments/assets/5cb0e8fc-c59a-48ec-bc35-082cf67fdaeb)
I can confirm that problem indeed exists. It's not possible to fill in any data on init page except for flight number. Shutting down the aircraft and realigning IRS doesn't helps. Even loading cold and dark state doesn't helps. Seems like the only way to have working FMS again is to return to main menu and start a new flight.

**Comment by tracernz** [comment] 2024-11-15 12:36
Duplicate of #9019.

**Closed by tracernz** 2024-11-15 12:36 UTC
Labels: Bug, A380X, MFD
