### ISSUE TITLE
A380 overcorrecting on aileron inputs 

### ISSUE THREAD

**Issue by colinlenzner** [flybywiresim/aircraft#9690] opened 2024-12-29 20:06 UTC
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-12-29T11:41:32+00:00",
    "ref": "refs/heads/master",
    "sha": "3bf143865cbe5e80276ae1de23eacf3aaf465d0b",
    "actor": "BravoMike99",
    "event_name": "manual",
    "pretty_release_name": "master:3bf14386",
    "version": "a380x-v0.13.0-dev.3bf1438"
}
```

### Describe the bug

When giving aileron inputs the aircraft tends to "overcorrect" onto the other side. e.g I give some sidestick input to the left and when I let go of the stick the aircraft gives a short input of the ailerons to the right.
I feel like with flaps extended the issue gets worse.

https://youtu.be/PtDehEfu57Q (video credit @Jaronics)

I use a Thrustmaster Airbus stick with reduced sensitivity and deadzones ingame.

Result: Hand flying is pretty hard, especially as on approach the aircraft tends to totally start weaving left to right making precise movements/approaches impossible.

### Expected behavior

The aircraft not doing that.

### Steps to reproduce

Start a flight and fly manually and start turning left and right

### References (optional)

https://youtu.be/PtDehEfu57Q

**Comment by donstim** [comment] 2024-12-31 13:16
This looks to be a duplicate of #9399

**Comment by leftseat380** [comment] 2024-12-31 15:12
Yes, it is still present. I think it is related to the triple aileron movement. You will notice some ailerons will move in the opposite direction when your roll input has stopped. It is designed in real life to counteract the large roll inertia due to the large wing and the weight of the outboard engines. I will try to increase the roll inertia in the FM to see if that helps.

**Comment by leftseat380** [comment] 2024-12-31 15:40
I tried increasing the roll inertia and roll stability, no joy. It still rolls the opposite way. It is tied into the fbw programming.

**Closed** 2024-12-31 16:12 UTC
Labels: Bug, A380X
