### ISSUE TITLE
Degrading performance on long haul flights

### ISSUE THREAD

**Issue by n4538-e1347** [flybywiresim/aircraft#5650] opened 2021-08-14 12:01 UTC
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-08-09T18:57:24+00:00",
  "ref": "v0.6.3",
  "sha": "7222a9516e4114742a7fec84080a2f63ea527428",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

After some hours of flight, typically more than 3-4 hours but it might depend on rig specs, performance is degrading with frame rate drops and crackling audio. It doesn't happen with revision 18573FC development.

### Expected behavior

Performance shouldn't degrade with time, as it doesn't happen with default planes nor with revision 18573FC development.

### Steps to reproduce

Just fly any route above 4 hourse and you should see degrading performance if using stable 0.63

### References (optional)

video showing degraded performance after a few hours: https://youtu.be/0z_ydRBzlgk . You can also hear the audio crackling when I pan around.  Same outside of the cockpit. I forgot to take a video when I entered development mode to show the frame rate but it was around 28 if I don't move anything but drops to 12 as soon as I start panning around the camera. Just plain stable 0.63.  It didn't happen while using default 747 on the same route and with same options. 

### Additional info (optional)

PC specs are i7-9700F, Win10 latest update, GTX 1660 6GB, 16 GB Ram, 1TB SSD dedicated to MSFS. CPU usage was around 72%, GPU between 33 and 42%, RAM 46% when I took the video. I noticed that in Task Manager the number of Handles is slowly increasing during the flight. I'm not sure it's a memory leak but it looks similar. I remember trying a few days ago, once I ended a flight with very poor frame rate, I exited to main menu then started anothe flight at the very same location and frame rate was still very poor like at the end of the previous flight. But quitting MSFS completely and immediately restarting it and restarting a new flight at the same location where I landed, performance was back to normal again. Could it be some process that's not being correctly handled once it's not necessary anymore and so it keeps accumulating hence lowering performance on the long run?

### Discord Username (optional)

Jackal#0862

**Comment by kutak11** [comment] 2021-08-14 15:37
I can confirm this, I just experienced terrible FPS on 6hrs flight to OMDB, after about 4 hrs FPS drops from 60 to 20 and about 14 on landing. Something went from with FPS after 3-4 hrs flight time.

**Comment by eze1510** [comment] 2021-08-14 18:03
I can confirm this as well - added another bug highlighting the same issues. If anyone has screenshots of the FPS at start and during flight with FPS drop and can add them to the other bug post would be great as I won't be around MSFS for a bit.

**Comment by n4538-e1347** [comment] 2021-08-14 23:13
Happened to me again but the problem is that it happened with PMP A330 (without compatibility patch!); FBW A320 development was installed as well in the community folder but I was using A330. But this time it happened after a longer time, >7hr so it might depend on MSFS itself or there might be more bugs at the same time. I'll try again in the next days with stable 0.63 and latest development and I'll make sure to record a video with FPS counter visible.

**Comment by kutak11** [comment] 2021-08-14 23:55
![fps drop2](https://user-images.githubusercontent.com/72166387/129462869-990dd257-1608-4a84-811f-2b258f936a5a.jpg)

it just reduce Main thread and Manipulators without any spikes... the longer flight is the more it goes down.

**Comment by marquinhosue** [comment] 2021-08-15 10:32
I have experienced the same, landing at O'Hare after more than 7 hours flying. Anyway, not sure if it is an Asobo or a FBW bug, since it's been my first flight lasting more than four hours. Has anybody perform a similar long flight with another aircraft? Unfortunately,  I have not my gaming computer available these days to check it, sorry :(

**Comment by SVitalini** [comment] 2021-08-15 11:03
Could be related to AI traffic. If the drop happens, disable ai traffic and see if fps recovers. Happened to me too. I disabled it and fos recovered, re-enabled it again and it was fine. Somehow, there seems to be an MSFS bug.

**Comment by marquinhosue** [comment] 2021-08-15 13:52
I don't think the cause in my case to be AI traffic . Mine was an IVAO flight, with neither real time traffic nor app multiplayer traffic activated. In addition, I forgot to mention in my previous post that I have experienced the issue with dev version (dated 11th August).

**Comment by kutak11** [comment] 2021-08-15 14:17
marquinhosue: huh absolutely the same, yesterday on IVAO flight do Dubai, I have never flown 6 hrs flight on msfs before. So it has something with traffic. Not FBW issue.

**Comment by n4538-e1347** [comment] 2021-08-15 19:13
> I have experienced the same, landing at O'Hare after more than 7 hours flying. Anyway, not sure if it is an Asobo or a FBW bug, since it's been my first flight lasting more than four hours. Has anybody perform a similar long flight with another aircraft? Unfortunately, I have not my gaming computer available these days to check it, sorry :(

I tried a long haul with default 747 and no other addon in my community folder and after 6 hours I had no performance issue. I'm currently trying again with A330 PMP (without FBW compatibility patch) and no issue whatsoever. I'm still interested in more testing with different combination of addons.

**Comment by n4538-e1347** [comment] 2021-08-15 19:15
> Could be related to AI traffic. If the drop happens, disable ai traffic and see if fps recovers. Happened to me too. I disabled it and fos recovered, re-enabled it again and it was fine. Somehow, there seems to be an MSFS bug.

I read someone saying it depended on Live Traffic, on MSFS forum. Are you talking about that or ar you talking about AI traffic too? I never use Live Traffic, so it can't be that. I also use some offline traffic but I recall once I tried disabling and reenabling it and it had no effect.

**Comment by tracernz** [comment] 2021-08-18 09:55
After a 4 hour flight with the aircraft fully powered down. Looks very much like a sim issue. ![image](https://user-images.githubusercontent.com/9995998/129876400-03688637-fe62-4711-80e0-28beab4549de.png)

**Comment by n4538-e1347** [comment] 2021-08-20 22:13
I reported this bug initially, but there might be more than one cause for the degrading performance. In my case, I noticed that for some reason I had some leftovers from a previous installation of MSFS that might have contributed and that I didn't notice when I first tested FBW A320 for this bug. After a fresh reinstall and more testing, I noticed that I can't reproduce this bug anymore UNLESS I have YourControls in my community folder. I tried again FBW stable and development version, A330 with FBW compatibility patch and default A320; tried at least 12 times flights longer than 5 hours and each time I experienced performance issues I had YourControls in my community folder (never used it, just installed it). Emptying the community folder and leaving YourControls only lead to a smooth flight for 3 hours, I still need to test on longer flights; I have already reported this possible issue on YourControls discord, but I'm really confused by this behaviour.

**Comment by G3NSVRV** [comment] 2021-12-28 19:25
happening on 0.7.3

**Comment by Mmucha83** [comment] 2021-12-29 12:15
Deleting "Your Controls" from community folder in deed helped also in my case.

maybe interesting:
https://devsupport.flightsimulator.com/questions/4657/wasm-execute-calculator-code-leaks-memory-and-redu.html

**Comment by G3NSVRV** [comment] 2021-12-29 12:34
> Deleting "Your Controls" from community folder in deed helped also in my case.
> 
> 
> 
> maybe interesting:
> 
> https://devsupport.flightsimulator.com/questions/4657/wasm-execute-calculator-code-leaks-memory-and-redu.html
> 
> 

@Mmucha83 as I mentioned on my closed thread, I don't have this and still experience this performance degradation; actually I'm just running vanilla FS2020 and the only addon that I have is this aircraft (0.7.3)

**Comment by dcherrie** [comment] 2022-03-12 12:11
This has started re-occurring in the past 1-2 weeks. 747 and 787 go fine for 14+ hours but flying the A320 for a few hours, just gets worse and worse in development.

This is after reinstalling the sim and the 2 airports I'm flying to and from, navigraph data and the livery I'm flying in the community folder.

**Comment by Benjozork** [comment] 2022-03-12 16:11
I believe SU8 introduced something that only affects certain planes.

If you could get timed screenshots of the __MSFS DevMode__ FPS counter, showing the thread timings over time, it would help a lot.

Additionally, can you provide the following info:

- What online features of MSFS are enabled / used;
- What AI/real-world traffic is enabled / used;
- What third party software connecting to the sim is used (vPilot, FSUIPC, etc.);
- Whether or not you have the YourControls add-on installed.

**Comment by kutak11** [comment] 2022-03-12 16:36
I can confirm this. After 2hrs flight the FPS drops. Where normaly I have more then 40 it drops to 30. On final less than 25 FPS where normaly I have 35+.
I use IVAO multiplayer + SimToolkit pro, MSFS multiplayer is disabled. I will try exactly the same flight without any of these addons.

**Comment by n4538-e1347** [comment] 2022-03-13 10:46
Adding some info. The very same problem happens with 0.63 stable, if it might be of any help. I know it's an outdated unsupported version but the problem lies probably in some old part of the code. No problem whatsoever until SU8. After SU8 performance starts degrading after 3 hours more or less. FS audio starts crackling when panning around the view (problem is mostly visible when panning the view, if I look straight forward audio is mostly fine). Also only FS audio is affected. I tried using SelfLoadingCargo and that program audio is fine even when FS audio is crackling. I still have to try with Asobo a320, and with only FBW a320 in my community folder. Right now the only content of the community folder was PMP a330 which I use together with 320 0.63 stable, and fsuipc-lvar-spad.next folders. I'll try without those too and report back. No YourControls folder. System is Win10, i7 9700f, 16gb ram, gtx 1660 6gb, 1TB dedicated ssd.

**Comment by AppleUK123** [comment] 2022-03-13 11:03
Hi I also am experiencing CPU Main thread degradation. The degradation is present on. both developer and experimental. No other aircraft including 3rd e.g, CRJ has this problem. If you need any more information let me know

System: Windows 10, 10900KF, 2070 Super, 32GB 3200mhz, 2TB M.2 SSD

**Comment by Benjozork** [comment] 2022-03-13 16:28
Screenshots of the MSFS FPS counter please. Cannot do anything without them.

**Comment by AppleUK123** [comment] 2022-03-13 23:18
**Report 1:** 
No other addons, RW 33 EGBB, 12 Noon, Clear Skies.
Loaded in. Then did one 360 degree pan in the external view, before going into flight deck.
Started timer. Took screenshots at 0min, 30 and 60mins.

As previously mentioned I do not have this issue in default aircraft and other 3rd party aircraft.
I can upload a HWInfo log if required

![00 00](https://user-images.githubusercontent.com/101504298/158083457-66265abd-4988-4e8f-b358-b53efbfc8999.png)
![30 00](https://user-images.githubusercontent.com/101504298/158083460-548d95ce-a740-4ed1-b2bf-cb68c72bfff2.png)
![60 00](https://user-images.githubusercontent.com/101504298/158083464-832edd83-7529-452c-b840-76ac2d8d0295.png)

**Comment by dcherrie** [comment] 2022-03-14 11:55
Anyone running AmbitiousPilots Toolbar Pushback? It's the culprit of major performance degradation since SU8 and the release of 1.4.0?

I'm currently flying without it and 1.5 hours into a flight with no performance degradation and mysteriously the CTD with MSFS have stopped.

**Comment by AppleUK123** [comment] 2022-03-14 12:04
No, I am not using Toolbar Pushback in those pictures above.
I have been using it in other flights and I have not experienced any adverse performance with it.

**Comment by AppleUK123** [comment] 2022-03-14 12:34
Further screenshots, even within 1 hour the CPU regression is clear to see.

Things I have tried (with no luck) include:

- Removing all addons
- Physically removing ethernet cable from PC and then reconnecting
- Disabling MSFS Cache
- Disabling Windows Page File
- Enabling Page File - twice size of RAM
- Changing MSFS graphics settings
- Closing developer mode then opening developer mode back up
- Clearing Standby RAM

![00 00](https://user-images.githubusercontent.com/101504298/158172928-8c45a1b8-7c44-42c3-a262-a42ba29d942b.png)
![1hr](https://user-images.githubusercontent.com/101504298/158172945-00f529ec-f39b-43ed-9c5a-adba8a7be83d.png)

**Comment by AppleUK123** [comment] 2022-03-14 13:49
Further update, cause of problem identified -  **FBW Developer/Experimental version.**

With the stable version I have **no** CPU degradation at all, so it is something 'contained' within the Dev/Exp version which I causing issues on my system.

Is there any way I can obtain older version of the developer FBW A320 to try and identify when the issue occurred? 
Hopefully the developers will now be able to identify exactly what code is the issue.

**Comment by BigCow74** [comment] 2022-03-14 13:50
I don't know if this will be useful, but I'll contribute a recent experience as well.  This was on an approximate 5-6 hour flight.  I left it alone while doing other things, and when I came back, FPS was around 3 (normally I'm @ 42 FPS in the cockpit).  Based on the attached Little Nav Map screen capture, you can see roughly where it degraded enough that autopilot was not able to keep it on track.  Also attached is the FPS counter near the end of the flight track.  This flight was using the Development version and was on March 10th, 2022

<img width="822" alt="VHHH-RJCK1" src="https://user-images.githubusercontent.com/101572828/158185615-a0146c8a-3458-4abd-9d2e-c9e0a90ce172.png">
<img width="411" alt="VHHH-RJCK2" src="https://user-images.githubusercontent.com/101572828/158185636-fc5baaab-0f95-430a-b74b-85099d99eff1.png">
.

**Comment by AppleUK123** [comment] 2022-03-15 18:42
If I turn the engines off the degradation stops and reverts back to the initial main thread timing when I first loaded in to the sim.  I did try turning off all displays initially but that did not stop the CPU regression. Hopefully this can help to identify the cause.

**Comment by dcherrie** [comment] 2022-03-17 14:44
Here is a screen record with the developer FPS showing after completing a 3.5 hour flight. The airport I started at was 40-60 fps, when landing down to 5-10 fps. After turning off all power to the aircraft, back up to 30+ fps. https://youtu.be/n5Qj4zAc3fcAfter completing the flight, went back to menu and reloaded in the exact place I had just landed, back to 40-60 fps.https://youtu.be/xHmEvlDTvN0I comfortably fly CJR on 3-4 hour flights and the Salty 747 and 787 Heavy Division on 15+ hour flights with absolutely no performance degradation. This is specific to the A320. Unsure if its present in the Asobo A320 or not but I highly doubt it. It's also not related to the Toolbar Pushback as once I discovered there was FPS degradation the day after install on all planes, I deleted it.On Mar 16, 2022, at 5:43 AM, AppleUK123 ***@***.***> wrote:If I turn the engines off the degradation stops and reverts back to the initial main thread timing when I first loaded in to the sim.  I did try turning off all displays initially but that did not stop the CPU regression. Hopefully this can help to identify the cause.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by dcherrie** [comment] 2022-03-17 14:54
Here is a screen record with the developer FPS showing after completing a 3.5 hour flight. The airport I started at was 40-60 fps, when landing down to 5-10 fps. After turning off all power to the aircraft, back up to 30+ fps.

https://youtu.be/n5Qj4zAc3fc

After completing the flight, went back to menu and reloaded in the exact place I had just landed, back to 40-60 fps.

https://youtu.be/xHmEvlDTvN0

I comfortably fly CJR on 3-4 hour flights and the Salty 747 and 787 Heavy Division on 15+ hour flights with absolutely no performance degradation. This is specific to the A320. Unsure if its present in the Asobo A320 or not but I highly doubt it. It's also not related to the Toolbar Pushback as once I discovered there was FPS degradation the day after install on all planes, I deleted it.

**Comment by AppleUK123** [comment] 2022-03-20 17:16
The MCDU web server fix has also resolved my CPU degradation over time which I have been recently reporting with Dev/Exp. Don't know if this was designed just to fix the stuttering or the degradation but nevertheless, CPU main thread is not decreasing with time.

**Comment by AppleUK123** [comment] 2022-03-24 13:10
I am continuing to experience performance degradation with the FBW Development and Experimental versions.

I have tried (unsuccessfully):
Disabling all online functionality in MSFS
NDU Fix
Disabling all addons
Game Mode Off and On (default is Off)
Disabling Page File
Enabling Page File twice the size of RAM (32GB Ram)
Deleting cache
Disabling/Enabling cache (default is enabled)
Turning all flight deck displays off (no change)
Changing MSFS Graphic settings
Locking FPS/ Turning V-Sync On or Off
Playing in windowed mode (default is fullscreen)
Disabling fullscreen optimisations
Disabling RAM compression

I have recently clean installed Windows 11 and I still experience Main Thread degradation. 
The degradation does not occur with any default MSFS aircraft and 3rd party aircraft (CRJ)
The degradation does not occur with the stable version.

It is my strong belief that the issue is something to do with the FBW Dev/Exp.
Please note I have MCDU Port set to permanently off via the EFB.

Test Setup:
10900K @5.1Ghz, 2TB Samsung 970 EVO Plus, 2070 Super, 32GB 3200Mhz RAM

Test Flight:
Location: RW33 EGBB Birmingham, UK. 
Time: 12PM
Weather: Clear Skies
Load up, then I start taking screenshots at 0mins and 30mins.
![Default A320 0mins](https://user-images.githubusercontent.com/101504298/159923158-8c107fc8-0914-4c53-a2b1-5d09c10a08f9.jpg)
![Default A320 30mins](https://user-images.githubusercontent.com/101504298/159923162-cd81a517-3118-4997-8743-325c375e6f38.jpg)
![Dev A320 0mins](https://user-images.githubusercontent.com/101504298/159923164-dc0a7501-6357-4eb2-9e11-b89b03b652b1.jpg)
![Dev A320 30mins](https://user-images.githubusercontent.com/101504298/159923168-f604dec1-b86d-4a31-92a5-4008e357dc18.jpg)

**Comment by Maximilian-Reuter** [comment] 2023-03-29 02:41
Is this still relevant ?

**Comment by tracernz** [comment] 2024-06-15 12:05
I think this is no longer relevant.

**Closed by tracernz** 2024-06-15 12:05 UTC
Labels: Bug, Asobo Bug, Performance
