### ISSUE TITLE
Doors opening at random when selecting the Service page mid-flight

### ISSUE THREAD

**Issue by drms-wav** [flybywiresim/aircraft#9262] opened 2024-11-01 10:24 UTC
### Aircraft Version

Development

### Build info

```json
"built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
```

### Describe the bug

Doors opened mid flight and selecting the service page on the tablet switches the opened doors from 1L to 2L, Cargo and Service door.

### Expected behavior

Doors not to open when mid flight.

### Steps to reproduce

Flight was EDDM-KSFO. 2x time acceleration used until descent. Bug happened in the descent stage ~ FL200

### References (optional)

<img width="1720" alt="Microsoft Flight Simulator Screenshot 2024 11 01 - 10 47 23 61" src="https://github.com/user-attachments/assets/c26aba9b-0628-4394-b1ea-df104170acbe">

### Discord Username (optional)

drms.wav

**Comment by aubinschneider13** [comment] 2024-11-01 10:50
Found a temporary solution, just change page again in the Flypad OS an put it to off and once its off doors wont move anymore. But each time you move from
![image](https://github.com/user-attachments/assets/f1746ce9-74f8-4f6e-8170-af0a0bc1a9a4)
to any other page on the flypad OS, it just change the doors position. So don't touch it

**Comment by moxiejeffdallas** [comment] 2024-11-01 15:03
Having same issue and can't find the fix.

**Comment by Saschl** [comment] 2024-11-01 15:06
Will be fixed with https://github.com/flybywiresim/aircraft/pull/9267

**Comment by Benjozork** [comment] 2024-11-01 15:07
Duplicate of  #9218

**Closed by Benjozork** 2024-11-01 15:07 UTC
Labels: Bug, A380X
