### ISSUE TITLE
Airplaine does not Startup

### ISSUE THREAD

**Issue by Road-to-Hell9** [flybywiresim/aircraft#8607] opened 2024-04-04 08:25 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-04-04T01:04:59+00:00",
    "ref": "refs/heads/master",
    "sha": "e73c4b58d60fbe67067e6eb81bff366c06d0b0ae",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:e73c4b58",
    "version": "a32nx-v0.12.0-dev.e73c4b5"
}
```

### Describe the bug

Aircraft Battery switches do noting, as well as External Powernothing

### Expected behavior

Batteries should start the Aircraft and Ground power should start the Screens

### Steps to reproduce

1. Load Flight
2. Press Battery Switches -- Noting Happens
3. Press Ground Power -- Notiong Happens

### Additional info (optional)

![Screenshot (4)](https://github.com/flybywiresim/aircraft/assets/69807128/cdcbb4c8-9436-4f38-9f62-a88a25fd5a8d)
![Screenshot (3)](https://github.com/flybywiresim/aircraft/assets/69807128/e023f4e8-efa5-4038-a3e4-0f8cb440e7db)

**Comment by tracernz** [comment] 2024-04-04 08:33
Either try enabling experimental UTF-8 support in Windows (https://docs.flybywiresim.com/fbw-a32nx/settings/#utf-8-support) or try SU15 beta which claims to fix this issue.

**Comment by Road-to-Hell9** [comment] 2024-04-04 08:52
Im afriad it still does not Work. Just tried it.

**Comment by ImenesFBW** [comment] 2024-04-04 09:14
Take a look at our known issues doc page;

 https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#broken-systems-black-screens-broken-cockpit-layout
 
 I'll close this as this is not a bug with A32NX, but a user system configuration issue.
 
 If you still face this issue after trying the documented fixes feel free to visit our support channel on Discord for further support

**Closed by ImenesFBW** 2024-04-04 09:14 UTC
Labels: Bug

**Comment by Road-to-Hell9** [comment] 2024-04-04 09:37
Thank you. I figured it out. It was the liveries of the Aircraft.
