### ISSUE TITLE
A320 HUD

### ISSUE THREAD

**Issue by Jasonjjgit** [flybywiresim/aircraft#8578] opened 2024-03-20 17:14 UTC
### Aircraft Version

Stable

### Description

Seems pretty straight forward. A heads up display.
![image_2024-03-20_191344523](https://github.com/flybywiresim/aircraft/assets/64889107/dfbbadec-3dc2-4e31-adf8-a370fae978c5)
 

### Discord Username (optional)

jasonjj

**Comment by tracernz** [comment] 2024-03-21 08:43
Duplicate of https://github.com/flybywiresim/aircraft/issues/3415

**Closed by tracernz** 2024-03-21 08:43 UTC
Labels: Request
