### ISSUE TITLE
A380X MSFS Save/Load

### ISSUE THREAD

**Issue by ajs117** [flybywiresim/aircraft#9278] opened 2024-11-01 16:29 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

MSFS default save/loading of aircraft state doesn't work. This is critical as it is a long-haul aircraft, most don't have 16+ hours to spare setting up and flying a transcontinental flight.

### Expected behavior

Be able to save a flight via MSFS save menu, exit the sim, load the flight from MSFS load menu and all parameters, switch states, flight plans etc are preserved and loaded.

### Steps to reproduce

Save flight
Load flight

**Comment by tracernz** [comment] 2024-11-02 07:09
Duplicate of #6178. A good idea, but tricky to do well when the systems are still under heavy development.

**Closed by tracernz** 2024-11-02 07:09 UTC
Labels: Request, A380X
