### ISSUE TITLE
Engine don’t start

### ISSUE THREAD

**Issue by Schummy75** [flybywiresim/aircraft#9357] opened 2024-11-03 09:30 UTC
### Aircraft Version

Development

### Build info

```json
Cx
```

### Describe the bug

Good evening everyone, sorry to write on your email but from the discord channel I could not find solution....
for a few months I can not start the engines of the a320 and now also of the a380... I have done hundreds of flights with the 320 but now nothing... obviously if I start the simulation from the runway everything works,,, but from the parking lot it does not start... the steps are always the same... i have tried to uninstall and reinstall as recommended via your installar but nothing.... i saw on discord that i'm not the only one having problems.. obviously i deleted all the community folder and checked msfs settings but i can't get out of it...if i use the standard 320 v2 i fly without problems..
can you somehow help me...?
i also attach pictures of the 380 if needed

i am confidently waiting
regards

### Expected behavior

Engine start progress

### Steps to reproduce

Air bleed on
Apu on and available
Fuel pump on

### Discord Username (optional)

Schummy75

**Comment by Benjozork** [comment] 2024-11-03 11:35
Duplicate of  #9210

**Closed by Benjozork** 2024-11-03 11:35 UTC
Labels: Bug, A380X
