### ISSUE TITLE
Wing Anti-Ice is Inop

### ISSUE THREAD

**Issue by donstim** [flybywiresim/aircraft#8387] opened 2024-01-07 01:42 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-05T14:10:10+00:00",
    "ref": "refs/heads/master",
    "sha": "5843e8e6d5bb4ea0850d23378a01f313ccaa7569",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:5843e8e6",
    "version": "v0.12.0-dev.5843e8e"
}
```

### Describe the bug

The wing anti-ice switch no longer works properly. It does not reduce the ice accreting on the wings in icing conditions.  See the following video:
https://1drv.ms/v/s!Ajsy7Ey4_8uFgZBj4J1YqtRD50yCJA?e=q8d4O7

At the beginning of the video, ice is accreting on the wing as can be seen by the increasing "Structural Ice PCT" simvar. After wing anti-ice is turned on, the "Structural Ice PCT" simvar continues to increase at the same rate. Although the "Structural Deice Switch"
simvar has changed on "1" (on), the activation of wing A/I has no effect on the rate of ice accretion.

This issue appears to be a bleed-related bug. Continuing with the video, when the APU bleed is opened with the wing A/I on, the "Structural Ice PCT" simvar starts decreasing. When the APU bleed is closed, it goes back to increasing. (Wing A/I must be activated, the APU must be on, and APU bleed open for the wing A/I to be operating properly.)

### Expected behavior

Accreted ice on the wings should be steadily reduced until it is eliminated when wing A/I is selected. 

### Steps to reproduce

1. Start at any reasonable altitude (I used 5000 feet)
2. Use the "Snow" weather preset in MSFS
3. Set a cloud layer that includes the altitude(s) you will be using
4. Set the cloud coverage to 100%
5. Use simvar watcher as shown in my video to observe the change in the "Structural Ice PCT" simvar to evaluate the effect of different selections on ice accretion.

### Additional info (optional)

I have an old A32NX PR build from 13 July 2023 where this worked properly.

### Discord Username (optional)

donbikes

**Comment by MicahBCode** [comment] 2024-01-09 12:05
This issue is fixed by #8388 isn't it?

**Comment by donstim** [comment] 2024-01-09 15:58
> This issue is fixed by #8388 isn't it?

No, that is an temporary disabling of icing effects until this bug is fixed.

**Comment by tracernz** [comment] 2024-01-09 17:28
The issue is that the crossbleed start PR disables the bleed air source when not starting engines.

**Comment by Maximilian-Reuter** [comment] 2024-01-10 06:04
https://discord.com/channels/738864299392630914/747571985831297145/1193632595234275450

Contains the Idea for how to fix this properly

**Comment by donstim** [comment] 2024-01-15 23:46
Hopefully someone will do it then.

**Comment by ArtemisPlayer** [comment] 2024-01-25 13:13
I can take a look but i cannot access the discord message to explain what should be fixed, can you post it here ?

**Comment by tracernz** [comment] 2024-01-25 21:28
The cross-bleed start PR disabled the bleed air source when engines aren't starting => anti-ice has no bleed air available.

**Comment by ArtemisPlayer** [comment] 2024-01-26 13:57
What makes you say that ? I can't find anything in the code that stops the engine bleed source when the starter is off. I will do some tests later, but that would mean that the anti-ice should work when APU bleed is off, but the starter is on (when engines are running)

**Comment by Maximilian-Reuter** [comment] 2024-01-26 15:58
> What makes you say that ? I can't find anything in the code that stops the engine bleed source when the starter is off. I will do some tests later, but that would mean that the anti-ice should work when APU bleed is off, but the starter is on (when engines are running)

![image](https://github.com/flybywiresim/aircraft/assets/5833783/a0bc303b-f564-4164-b38c-8c182fe9767d)
the issue originates in this piece of rust code where the engines get toggled as a bleed source when the engine starter gets depressurized

**Comment by ngreatorex** [comment] 2024-01-26 16:01
Link to function in question:
https://github.com/flybywiresim/aircraft/blob/cf1e4f4a3cebd96c68cdc4e82f6a1a6d875403ef/fbw-common/src/wasm/systems/systems_wasm/src/engines.rs#L10

**Comment by ArtemisPlayer** [comment] 2024-01-29 15:12
> Basically the plan is to remove that part of the code as it is no longer necessary to mess with the bleed source selection.

Yet, when I run the code removing the `toggle_sim_engine_bleed_air`, engines do not appear as a bleed air source. (BLEED AIR ENGINE stays to 0, BLEED AIR SOURCE CONTROL to 2 (apu)).
 
> Instead we want to control the actual event K:TOGGLE_STRUCTURAL_DEICE ourselves in the WingAntiIce code in Rust.

👍 

> The switch on the overhead then should no longer set that event but instead use the variable that it is copied into already BUTTON_OVHD_ANTI_ICE_WING_POSITION

That's indeed already done, I think.

I will do a PR with some modifications: 
- Removing the modification of the engine bleed air source status.
- Setting the engines as bleed air source as long as they are running and the bleed p/b of the engine is on auto.
- Calling K:TOGGLE_STRUCTURAL_DEICE based on the bleed consumption (and temperature) of the WAI. 

That would be my first real issue (I think it would help understand how the Rust part of the project works), so do not hesitate to make any comment.

**Comment by ngreatorex** [comment] 2024-01-29 20:47
> > The switch on the overhead then should no longer set that event but instead use the variable that it is copied into already BUTTON_OVHD_ANTI_ICE_WING_POSITION
> 
> That's indeed already done, I think.

I don't think it is. This line still references the K event:
https://github.com/flybywiresim/aircraft/blob/41f8f0b7acc1ad2483e67bd7b7f851a0ac1c36c4/fbw-a32nx/src/behavior/src/A32NX_Interior_Misc.xml#L245

> 
> I will do a PR with some modifications:
> 
> * Removing the modification of the engine bleed air source status.
> * Setting the engines as bleed air source as long as they are running and the bleed p/b of the engine is on auto.
> * Calling K:TOGGLE_STRUCTURAL_DEICE based on the bleed consumption (and temperature) of the WAI.
> 
> That would be my first real issue (I think it would help understand how the Rust part of the project works), so do not hesitate to make any comment.
> 
> Edit : we can also chat on discord (u: ArtemisPlayer)

I actually worked on this over the weekend! I guess I should have posted here that I was planning to. Hope you haven't done too much so we're not duplicating work. I've committed and pushed my work to https://github.com/ngreatorex/flybywiresim-aircraft/tree/fix-anti-ice. The only issue left is that I want it to work better with GSX. GSX de-ice turns on WING ANTI ICE by calling K:TOGGLE_STRUCTURAL_DEICE directly. At the moment, this won't illuminate the push button anymore. Should be a relatively simply fix - once I've done that I was planning to open a PR.

I've just reaslised I actually missed the part of the comment above that mentioned removing the bleed air source code, so instead I just added a check for whether the engines were running.

**Comment by ArtemisPlayer** [comment] 2024-01-29 21:52
> I actually worked on this over the weekend! I guess I should have posted here that I was planning to. Hope you haven't done too much so we're not duplicating work. I've committed and pushed my work to https://github.com/ngreatorex/flybywiresim-aircraft/tree/fix-anti-ice. The only issue left is that I want it to work better with GSX. GSX de-ice turns on WING ANTI ICE by calling K:TOGGLE_STRUCTURAL_DEICE directly. At the moment, this won't illuminate the push button anymore. Should be a relatively simply fix - once I've done that I was planning to open a PR.
> 
> I've just reaslised I actually missed the part of the comment above that mentioned removing the bleed air source code, so instead I just added a check for whether the engines were running.

Nice work ! I worked a bit on it, but it was far from being finished. I took a look at your changes, everything looks fine. 

Maybe the following code will cause issues with add-ons (you mentioned GSX):
```Rust
     builder.on_change(
          ExecuteOn::PostTick,
          vec![Variable::named("PNEU_WING_ANTI_ICE_SYSTEM_ON")],
          Box::new(move |prev_values, new_values| {
              let prev_wing_anti_ice_on = to_bool(prev_values[0]);
              let new_wing_anti_ice_on = to_bool(new_values[0]);

              if new_wing_anti_ice_on != prev_wing_anti_ice_on {
                  execute_calculator_code::<()>("(>K:TOGGLE_STRUCTURAL_DEICE)");
              }
          }),
      );
```
because it does not check a state but only toggles the deice system according to the changes of PNEU_WING_ANTI_ICE_SYSTEM_ON. A better solution may be to check the state with (I think) [STRUCTURAL_DEICE_SWITCH](https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_System_Variables.htm#STRUCTURAL_DEICE_SWITCH). So you get something like this (not tested):

```Rust
pub(super) fn wing_anti_ice() -> impl FnOnce(&mut MsfsAspectBuilder) -> Result<(), Box<dyn Error>> {
    move |builder: &mut MsfsAspectBuilder| {
        builder.on_change(
            ExecuteOn::PostTick,
            vec![
                Variable::named("PNEU_WING_ANTI_ICE_SYSTEM_ON"),
                Variable::aircraft("STRUCTURAL DEICE SWITCH", "bool", 0),],
            Box::new(move |_, values| {
                let wing_anti_ice_system_on = to_bool(values[0]);
                let is_deicing = to_bool(values[1]);

                if is_deicing != wing_anti_ice_system_on{
                    execute_calculator_code::<()>("(>K:TOGGLE_STRUCTURAL_DEICE)");
                }
            }),
        );

        Ok(())
    }
}
```

**Comment by Maximilian-Reuter** [comment] 2024-01-29 22:16
> > > The switch on the overhead then should no longer set that event but instead use the variable that it is copied into already BUTTON_OVHD_ANTI_ICE_WING_POSITION
> > 
> > 
> > That's indeed already done, I think.
> 
> I don't think it is. This line still references the K event:
> 
> https://github.com/flybywiresim/aircraft/blob/41f8f0b7acc1ad2483e67bd7b7f851a0ac1c36c4/fbw-a32nx/src/behavior/src/A32NX_Interior_Misc.xml#L245
> 
> > I will do a PR with some modifications:
> > 
> > * Removing the modification of the engine bleed air source status.
> > * Setting the engines as bleed air source as long as they are running and the bleed p/b of the engine is on auto.
> > * Calling K:TOGGLE_STRUCTURAL_DEICE based on the bleed consumption (and temperature) of the WAI.
> > 
> > That would be my first real issue (I think it would help understand how the Rust part of the project works), so do not hesitate to make any comment.
> > Edit : we can also chat on discord (u: ArtemisPlayer)
> 
> I actually worked on this over the weekend! I guess I should have posted here that I was planning to. Hope you haven't done too much so we're not duplicating work. I've committed and pushed my work to https://github.com/ngreatorex/flybywiresim-aircraft/tree/fix-anti-ice. The only issue left is that I want it to work better with GSX. GSX de-ice turns on WING ANTI ICE by calling K:TOGGLE_STRUCTURAL_DEICE directly. At the moment, this won't illuminate the push button anymore. Should be a relatively simply fix - once I've done that I was planning to open a PR.
> 
> I've just reaslised I actually missed the part of the comment above that mentioned removing the bleed air source code, so instead I just added a check for whether the engines were running.

I suggest you make a pullrequest in draft mode, that way everyone can comment on the actual code and help with suggestions if needed ;) Thanks for taking this on btw

**Comment by ngreatorex** [comment] 2024-01-29 23:59
> I suggest you make a pullrequest in draft mode, that way everyone can comment on the actual code and help with suggestions if needed ;) Thanks for taking this on btw

👍Done! #8454

> Maybe the following code will cause issues with add-ons (you mentioned GSX):
> 
> ```rust
>      builder.on_change(
>           ExecuteOn::PostTick,
>           vec![Variable::named("PNEU_WING_ANTI_ICE_SYSTEM_ON")],
>           Box::new(move |prev_values, new_values| {
>               let prev_wing_anti_ice_on = to_bool(prev_values[0]);
>               let new_wing_anti_ice_on = to_bool(new_values[0]);
> 
>               if new_wing_anti_ice_on != prev_wing_anti_ice_on {
>                   execute_calculator_code::<()>("(>K:TOGGLE_STRUCTURAL_DEICE)");
>               }
>           }),
>       );
> ```
> 
> because it does not check a state but only toggles the deice system according to the changes of PNEU_WING_ANTI_ICE_SYSTEM_ON. A better solution may be to check the state with (I think) [STRUCTURAL_DEICE_SWITCH](https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_System_Variables.htm#STRUCTURAL_DEICE_SWITCH). So you get something like this (not tested):
> 
> ```rust
> pub(super) fn wing_anti_ice() -> impl FnOnce(&mut MsfsAspectBuilder) -> Result<(), Box<dyn Error>> {
>     move |builder: &mut MsfsAspectBuilder| {
>         builder.on_change(
>             ExecuteOn::PostTick,
>             vec![
>                 Variable::named("PNEU_WING_ANTI_ICE_SYSTEM_ON"),
>                 Variable::aircraft("STRUCTURAL DEICE SWITCH", "bool", 0),],
>             Box::new(move |_, values| {
>                 let wing_anti_ice_system_on = to_bool(values[0]);
>                 let is_deicing = to_bool(values[1]);
> 
>                 if is_deicing != wing_anti_ice_system_on{
>                     execute_calculator_code::<()>("(>K:TOGGLE_STRUCTURAL_DEICE)");
>                 }
>             }),
>         );
> 
>         Ok(())
>     }
> }
> ```

The reason I haven't done this again comes down to GSX - once GSX toggles on the STRUCTURAL DEICE in the sim, I want to leave it on while on the ground. Otherwise, due to the fact that the wing anti ice only works on the ground for the 30 second test, you would get ice accumulating during taxi. Obviously if MSFS supported separate DEICE and ANTI ICE then this wouldn't be necessary, maybe in MSFS2024 😄 . Anyway, we can move the code discussion to the PR.

**Closed** 2024-02-04 18:22 UTC
Labels: Bug
