### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Goritoo11** [flybywiresim/aircraft#9298] opened 2024-11-01 23:50 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

Some textures in the 4k variant aren't 4k but 8k so I recommend to downscale every 8k texture to 4k, every 4k to 2k and every 2k texture to 1080p

### Expected behavior

Better performance

### Steps to reproduce

Just load up your plane and see the bad performance

**Comment by Benjozork** [comment] 2024-11-01 23:51
Duplicate of  #8931

**Closed by Benjozork** 2024-11-01 23:51 UTC
Labels: Bug, A380X
