### ISSUE TITLE
MSFS2024: CPNY F-PLN REQUEST on MCDU Cause a Crash.

### ISSUE THREAD

**Issue by NoobMasterRace** [flybywiresim/aircraft#9590] opened 2024-11-25 18:49 UTC
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-23T01:07:37+00:00",
    "ref": "refs/heads/master",
    "sha": "f484bde87a08f6d3c0c67f46dc1e953b474fc583",
    "actor": "lukecologne",
    "event_name": "manual",
    "pretty_release_name": "master:f484bde8",
    "version": "a380x-v0.13.0-dev.f484bde"
}
```

### Describe the bug

CPNY F-PLN REQUEST on MCDU Cause a Crash.

### Expected behavior

F-PLN is received and displayed correctly on the MCDU.

### Steps to reproduce

1. import simbrief data on EFB.
2. press CMPNY F-PLN REQUEST 
3. CRASH

**Comment by Benjozork** [comment] 2024-11-25 18:52
Duplicate of #9574

**Closed** 2024-11-25 18:52 UTC
Labels: Bug, A380X
