### ISSUE TITLE
Thrust Detent Toggle/Increment Feature for Controller Users

### ISSUE THREAD

**Issue by marxio09dio** [flybywiresim/aircraft#9178] opened 2024-10-29 18:06 UTC
### Aircraft Version

Development

### Description

As a controller user, it’s challenging to precisely adjust thrust and stop at each thrust detent (e.g., CL, FLEX, TOGA).
A feature that would allow users to toggle between thrust detents using a button or keybind, providing more precise control over thrust settings during flight, would be really helpful.

Suggested Solutions:

Incremental Thrust Detent Toggle: Similar to what Fenix does, an option to either toggle between incremental thrust or scroll through the various detents

Direct Detent Keybindings: Alternatively, as FSLABs do, normal thrust but keys like F1 and F4 scroll to the various detents.

**Comment by tracernz** [comment] 2024-10-29 18:11
It's a good idea, and duplicate of https://github.com/flybywiresim/aircraft/issues/9131

**Closed by tracernz** 2024-10-29 18:11 UTC
Labels: Request
