### ISSUE TITLE
APU  MASTER - ENG 1 MASTER

### ISSUE THREAD

**Issue by NoobMasterRace** [flybywiresim/aircraft#9589] opened 2024-11-25 18:02 UTC
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-23T01:07:37+00:00",
    "ref": "refs/heads/master",
    "sha": "f484bde87a08f6d3c0c67f46dc1e953b474fc583",
    "actor": "lukecologne",
    "event_name": "manual",
    "pretty_release_name": "master:f484bde8",
    "version": "a380x-v0.13.0-dev.f484bde"
}
```

### Describe the bug

when pressing APU MASTER switch, ENG 1 MASTER going into OFF position.

### Expected behavior

ENG MASTER STAYS ON

### Steps to reproduce

1. Normal ENG start procedure 
2. APU master to OFF

**Comment by Saschl** [comment] 2024-11-25 18:32
This is MSFS2024 related. Will be fixed by https://github.com/flybywiresim/aircraft/pull/9583

**Comment by tracernz** [comment] 2024-11-25 19:49
Duplicate of #9575 and FS2024 is not supported.

**Closed by tracernz** 2024-11-25 19:49 UTC
Labels: Bug, A380X
