### ISSUE TITLE
FMS not fully reset at the end of a flight

### ISSUE THREAD

**Issue by geninguillaume** [flybywiresim/aircraft#9286] opened 2024-11-01 19:22 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

After landing, part of the FMS resets. However, the perf page of the FMS remains stuck on the APPR mode.
When uploading a new flight plan, the PERF page cannot be used as blocked from previous flight. Impossible to set takeoff perfo for the new flight.

### Expected behavior

As for the A32NX, when completing the flight, the FMS resets for the next flight.

### Steps to reproduce

1. perform a flight with a successful landing
2. taxi to gate (or stop wherever you want)
3. shutdown engines
4. load new flight
5. go to PERF page = it is stuck to the previous flight APPR page for landing.

### Discord Username (optional)

fguge

**Comment by tracernz** [comment] 2024-11-02 01:42
Duplicate of https://github.com/flybywiresim/aircraft/issues/9019

**Closed by tracernz** 2024-11-02 01:42 UTC
Labels: Bug, A380X
